name: sharding-repl-cache

services:
  #сервер конфигурации
  configSrv:
    image: mongo:latest 
    container_name: configSrv 
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr", 
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27019"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #1-ая реплика 1-ого шарда
  shard1-1:
    image: mongo:latest
    container_name: shard1-1
    restart: always
    ports:
      - "27021:27018"
    networks:
      app-network:
    volumes:
      - shard1-1-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1",
        "--bind_ip_all"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #2-ая реплика 1-ого шарда
  shard1-2:
    image: mongo:latest
    container_name: shard1-2
    restart: always
    ports:
      - "27022:27018"
    networks:
      app-network:
    volumes:
      - shard1-2-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1",
        "--bind_ip_all"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #3-я реплика 1-ого шарда
  shard1-3:
    image: mongo:latest
    container_name: shard1-3
    restart: always
    ports:
      - "27023:27018"
    networks:
      app-network:
    volumes:
      - shard1-3-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1",
        "--bind_ip_all"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #1-ая реплика 2-ого шарда
  shard2-1:
    image: mongo:latest
    container_name: shard2-1
    restart: always
    ports:
      - "27031:27018"
    networks:
      app-network:
    volumes:
      - shard2-1-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #2-ая реплика 2-ого шарда
  shard2-2:
    image: mongo:latest
    container_name: shard2-2
    restart: always
    ports:
      - "27032:27018"
    networks:
      app-network:
    volumes:
      - shard2-2-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #3-я реплика 2-ого шарда
  shard2-3:
    image: mongo:latest
    container_name: shard2-3
    restart: always
    ports:
      - "27033:27018"
    networks:
      app-network:
    volumes:
      - shard2-3-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard2",
        "--bind_ip_all"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  #роутер
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos",
        "--configdb", 
        "config_server/configSrv:27019",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_data:/data

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    platform: linux/amd64
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    networks:
      app-network:
    environment:
      MONGODB_URL: "mongodb://mongos_router"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-data:

  shard1-1-data:
  shard1-2-data:
  shard1-3-data:

  shard2-1-data:
  shard2-2-data:
  shard2-3-data:

  redis_data:
